export const DATA_LOADING = 'home/DATA_LOADING';
export const DATA_AVAILABLE = 'home/DATA_AVAILABLE';

export const CHECKLISTS_LOADING = 'home/CHECKLISTS_LOADING';
export const CHECKLISTS_AVAILABLE = 'home/CHECKLISTS_AVAILABLE';

export const CHECKLIST_AVAILABLE = 'home/CHECKLIST_AVAILABLE';
export const RECENT_TAB1_AVAILABLE = 'home/RECENT_TAB1_AVAILABLE';
export const RECENT_TAB2_AVAILABLE = 'home/RECENT_TAB2_AVAILABLE';
export const RECENT_TAB3_AVAILABLE = 'home/RECENT_TAB3_AVAILABLE';
